spring.application.name=project-aarambh


spring.datasource.url=jdbc:h2:mem:dbAarambh
spring.datasource.driverClassName=org.h2.Driver

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
# this works for all db as everytime it doesn't create anew table on starting rather if it founds one already created so it will simply update it



# so there was no problem until Spring 2.7 it started after that: the problem was that the data.sql executed before the table was even created
# to delay that to tell it the exact sequence use the following statement

spring.jpa.defer-datasource-initialization=true
# this delays the database initialization so that the table is created before the initialization of data




spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB